version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: alpainfra-prometheus
    restart: unless-stopped
    expose:
      - 9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    # extra_hosts:
    #   - 'host.docker.internal:${HOST_IP}'
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-plugins:/var/lib/grafana/plugins
      - grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    # extra_hosts:
    #   - 'host.docker.internal:${HOST_IP}'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  grafana-plugins:
    driver: local
  grafana-provisioning:
    driver: local
