global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'adb_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/adb/metrics'
