{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "work",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Query Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Android Query Time",
   "type": "trend",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$[*]" }
     ],
     "method": "GET",
     "urlPath": "/works/$work/android/time"
    }
   ]
  },
  { "title": "Host Query Time (작업중)", "type": "trend", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 } },
  { "title": "VDBE Profile (작업중)", "type": "trend", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 } },
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "cpu usage" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    { "expr": "disk_available", "legendFormat": "Available" },
    { "expr": "disk_used", "legendFormat": "Used" },
    { "expr": "disk_usage_percent", "legendFormat": "Percentate" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mem_total", "legendFormat": "Total" },
    { "expr": "mem_used", "legendFormat": "Used" }
   ]
  }
 ]
}